/**
 * Auto-generated by: https://github.com/pmndrs/gltfjsx
 */

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber'

export default function (props: GroupProps & {src: string}) {
  const group = React.useRef()
  const { src, ...other } = props
  // @ts-ignore
  const { nodes, materials } = useGLTF(src)
  return (
    <group ref={group} {...other} dispose={null}>
      <group rotation-x={Math.PI / 2}>
        <mesh geometry={nodes.Red_light_button_00.geometry} material={nodes.Red_light_button_00.material} />
        <mesh geometry={nodes.Red_light_button_01.geometry} material={nodes.Red_light_button_01.material} />
        <mesh geometry={nodes.Red_light_button_02.geometry} material={nodes.Red_light_button_02.material} />
        <mesh geometry={nodes.Red_light_button_03.geometry} material={nodes.Red_light_button_03.material} />
        <mesh geometry={nodes.Red_light_button_04.geometry} material={nodes.Red_light_button_04.material} />
        <mesh geometry={nodes.Red_light_button_05.geometry} material={nodes.Red_light_button_05.material} />
        <mesh geometry={nodes.Red_light_button_06.geometry} material={nodes.Red_light_button_06.material} />
        <mesh geometry={nodes.Red_light_button_07.geometry} material={nodes.Red_light_button_07.material} />
        <mesh geometry={nodes.Red_light_button_08.geometry} material={nodes.Red_light_button_08.material} />
        <mesh geometry={nodes.Red_light_button_09.geometry} material={nodes.Red_light_button_09.material} />
        <mesh geometry={nodes.Red_light_button_10.geometry} material={nodes.Red_light_button_10.material} />
        <mesh geometry={nodes.Red_light_button_11.geometry} material={nodes.Red_light_button_11.material} />
        <mesh geometry={nodes.Red_light_button_12.geometry} material={nodes.Red_light_button_12.material} />
        <mesh geometry={nodes.Red_light_button_13.geometry} material={nodes.Red_light_button_13.material} />
        <mesh geometry={nodes.Red_light_button_14.geometry} material={nodes.Red_light_button_14.material} />
        <mesh geometry={nodes.Red_light_button_15.geometry} material={nodes.Red_light_button_15.material} />
        <mesh geometry={nodes.Cue_metal_L.geometry} material={nodes.Cue_metal_L.material} />
        <mesh geometry={nodes.PlayPause_L.geometry} material={nodes.PlayPause_L.material} />
        <mesh geometry={nodes.PlayPause_R.geometry} material={nodes.PlayPause_R.material} />
        <mesh geometry={nodes.Cue_metal_R.geometry} material={nodes.Cue_metal_R.material} />
        <mesh geometry={nodes.Tempo_panel_L.geometry} material={nodes.Tempo_panel_L.material} />
        <mesh geometry={nodes.Inst_buttons.geometry} material={nodes.Inst_buttons.material} />
        <mesh geometry={nodes.Cue_orange_button_02.geometry} material={nodes.Cue_orange_button_02.material} />
        <mesh geometry={nodes.Cue_orange_button_01.geometry} material={nodes.Cue_orange_button_01.material} />
        <mesh geometry={nodes.Cue_orange_button_00.geometry} material={nodes.Cue_orange_button_00.material} />
        <mesh geometry={nodes.Tempo_panel_R.geometry} material={nodes.Tempo_panel_R.material} />
        <mesh geometry={nodes.DJ_Mixer_1.geometry} material={materials['Frame_plastic.001']} />
        <mesh geometry={nodes.DJ_Mixer_2.geometry} material={materials['Back_plastic.001']} />
        <mesh geometry={nodes.FX_Selecr_button.geometry} material={materials['rubber_FXSelect.001']} />
        <mesh geometry={nodes.Release_button.geometry} material={materials['Blue_light.001']} />
        <mesh geometry={nodes.Plate_diod.geometry} material={materials['Dark_plastic.001']} />
        <mesh geometry={nodes.Light_diod.geometry} material={materials['Diod.001']}  />
        <mesh geometry={nodes.Phones_jack_detail1.geometry} material={materials['METAL_jack_gold.001']} />
        <mesh geometry={nodes.R_Jack_part017.geometry} material={materials['Paint_white.001']} />
        <mesh geometry={nodes.R_Jack_part015.geometry} material={materials['Paint_red.001']} />
        <mesh geometry={nodes.R_Jack_part016.geometry} material={materials['Metal_jack.001']} />
        <mesh geometry={nodes.Front_panel.geometry} material={materials['Front_plastic.001']} />
        <mesh geometry={nodes.Beat_plate.geometry} material={nodes.Beat_plate.material}  />
        <mesh geometry={nodes.Master_plate.geometry} material={nodes.Master_plate.material} />
        <mesh geometry={nodes.Controller_022_1.geometry} material={nodes.Controller_022_1.material} />
        <mesh geometry={nodes.Controller_022_2.geometry} material={nodes.Controller_022_2.material} />
        <mesh geometry={nodes.Plastic_caps.geometry} material={nodes.Plastic_caps.material} />
        <mesh geometry={nodes.Plate_Center.geometry} material={nodes.Plate_Center.material} />
        <mesh geometry={nodes.Glass_center.geometry} material={nodes.Glass_center.material} />
        <mesh geometry={nodes.Master_button.geometry} material={nodes.Master_button.material} />
        <mesh geometry={nodes.Phones_jack.geometry} material={nodes.Phones_jack.material} />
        <mesh geometry={nodes.Beat_sync_button.geometry} material={nodes.Beat_sync_button.material} />
        <mesh geometry={nodes.Glass_left.geometry} material={nodes.Glass_left.material}  />
        <mesh geometry={nodes.Turn_Controller_plate_L.geometry} material={nodes.Turn_Controller_plate_L.material} />
        <mesh geometry={nodes.Pad_button.geometry} material={nodes.Pad_button.material}  />
        <mesh geometry={nodes.In_adjust_button.geometry} material={nodes.In_adjust_button.material} />
        <mesh geometry={nodes.Active_loop_button.geometry} material={nodes.Active_loop_button.material} />
        <mesh geometry={nodes.Call_button.geometry} material={nodes.Call_button.material} />
        <mesh geometry={nodes.Phones_jack_detail2.geometry} material={nodes.Phones_jack_detail2.material} />
        <mesh geometry={nodes.Metal_handle.geometry} material={nodes.Metal_handle.material} />
        <mesh geometry={nodes.Plate_shift.geometry} material={nodes.Plate_shift.material} />
        <mesh geometry={nodes.Shift_button_L.geometry} material={nodes.Shift_button_L.material} />
        <mesh geometry={nodes.Screw.geometry} material={nodes.Screw.material}  />
        <mesh geometry={nodes.Level_Control.geometry} material={nodes.Level_Control.material} />
        <mesh geometry={nodes.USB_jack.geometry} material={nodes.USB_jack.material}  />
        <mesh geometry={nodes.Tempo_controller_1.geometry} material={nodes.Tempo_controller_1.material} />
        <mesh geometry={nodes.Tempo_controller_2.geometry} material={nodes.Tempo_controller_2.material} />
        <mesh geometry={nodes.Turn_Controller_L.geometry} material={nodes.Turn_Controller_L.material} />
        <mesh geometry={nodes.Plate_L.geometry} material={nodes.Plate_L.material}  />
        <mesh geometry={nodes.Legs.geometry} material={nodes.Legs.material}  />
        <mesh geometry={nodes.Glass_right.geometry} material={nodes.Glass_right.material} />
        <mesh geometry={nodes.Turn_Controller_plate_R.geometry} material={nodes.Turn_Controller_plate_R.material} />
        <mesh geometry={nodes.Out_adjust_button2.geometry} material={nodes.Out_adjust_button2.material} />
        <mesh geometry={nodes.Plate_R.geometry} material={nodes.Plate_R.material}  />
        <mesh geometry={nodes.In_adjust_button2.geometry} material={nodes.In_adjust_button2.material} />
        <mesh geometry={nodes.Call_button2.geometry} material={nodes.Call_button2.material} />
        <mesh geometry={nodes.Out_adjust_button.geometry} material={nodes.Out_adjust_button.material} />
        <mesh geometry={nodes.Pad_button_right.geometry} material={nodes.Pad_button_right.material} />
        <mesh geometry={nodes.Plate_shift_r.geometry} material={nodes.Plate_shift_r.material} />
        <mesh geometry={nodes.Shift_button_R.geometry} material={nodes.Shift_button_R.material} />
        <mesh geometry={nodes.PP_plate.geometry} material={nodes.PP_plate.material}  />
        <mesh geometry={nodes.Tempo_controller002_1.geometry} material={nodes.Tempo_controller002_1.material} />
        <mesh geometry={nodes.Tempo_controller002_2.geometry} material={nodes.Tempo_controller002_2.material} />
        <mesh geometry={nodes.Metal_handle_right.geometry} material={nodes.Metal_handle_right.material} />
        <mesh geometry={nodes.Effect_Controls_00_1.geometry} material={nodes.Effect_Controls_00_1.material} />
        <mesh geometry={nodes.Effect_Controls_00_2.geometry} material={nodes.Effect_Controls_00_2.material} />
        <mesh geometry={nodes.Effect_Controls_00_3.geometry} material={nodes.Effect_Controls_00_3.material} />
        <mesh geometry={nodes.Effect_Controls_01_1.geometry} material={nodes.Effect_Controls_01_1.material} />
        <mesh geometry={nodes.Effect_Controls_01_2.geometry} material={nodes.Effect_Controls_01_2.material} />
        <mesh geometry={nodes.Effect_Controls_01_3.geometry} material={nodes.Effect_Controls_01_3.material} />
        <mesh geometry={nodes.Effect_Controls_02_1.geometry} material={materials.Base_Metal} />
        <mesh geometry={nodes.Effect_Controls_02_2.geometry} material={materials.Top} />
        <mesh geometry={nodes.Effect_Controls_03_1.geometry} material={nodes.Effect_Controls_03_1.material} />
        <mesh geometry={nodes.Effect_Controls_03_2.geometry} material={nodes.Effect_Controls_03_2.material} />
        <mesh geometry={nodes.Effect_Controls_03_3.geometry} material={nodes.Effect_Controls_03_3.material} />
        <mesh geometry={nodes.Effect_Controls_04_1.geometry} material={nodes.Effect_Controls_04_1.material} />
        <mesh geometry={nodes.Effect_Controls_04_2.geometry} material={nodes.Effect_Controls_04_2.material} />
        <mesh geometry={nodes.Effect_Controls_04_3.geometry} material={nodes.Effect_Controls_04_3.material} />
        <mesh geometry={nodes.Effect_Controls_05_1.geometry} material={nodes.Effect_Controls_05_1.material} />
        <mesh geometry={nodes.Effect_Controls_05_2.geometry} material={nodes.Effect_Controls_05_2.material} />
        <mesh geometry={nodes.Effect_Controls_05_3.geometry} material={nodes.Effect_Controls_05_3.material} />
        <mesh geometry={nodes.Effect_Controls_06_1.geometry} material={nodes.Effect_Controls_06_1.material} />
        <mesh geometry={nodes.Effect_Controls_06_2.geometry} material={nodes.Effect_Controls_06_2.material} />
        <mesh geometry={nodes.Effect_Controls_06_3.geometry} material={nodes.Effect_Controls_06_3.material} />
        <mesh geometry={nodes.Effect_Controls_07_1.geometry} material={nodes.Effect_Controls_07_1.material} />
        <mesh geometry={nodes.Effect_Controls_07_2.geometry} material={nodes.Effect_Controls_07_2.material} />
        <mesh geometry={nodes.Effect_Controls_07_3.geometry} material={nodes.Effect_Controls_07_3.material} />
        <mesh geometry={nodes.Effect_Controls_08_1.geometry} material={nodes.Effect_Controls_08_1.material} />
        <mesh geometry={nodes.Effect_Controls_08_2.geometry} material={nodes.Effect_Controls_08_2.material} />
        <mesh geometry={nodes.Effect_Controls_08_3.geometry} material={nodes.Effect_Controls_08_3.material} />
        <mesh geometry={nodes.Effect_Controls_09_1.geometry} material={nodes.Effect_Controls_09_1.material} />
        <mesh geometry={nodes.Effect_Controls_09_2.geometry} material={nodes.Effect_Controls_09_2.material} />
        <mesh geometry={nodes.Effect_Controls_09_3.geometry} material={nodes.Effect_Controls_09_3.material} />
        <mesh geometry={nodes.Effect_Controls_10_1.geometry} material={nodes.Effect_Controls_10_1.material} />
        <mesh geometry={nodes.Effect_Controls_10_2.geometry} material={nodes.Effect_Controls_10_2.material} />
        <mesh geometry={nodes.Effect_Controls_10_3.geometry} material={nodes.Effect_Controls_10_3.material} />
        <mesh geometry={nodes.Effect_Controls_11_1.geometry} material={nodes.Effect_Controls_11_1.material} />
        <mesh geometry={nodes.Effect_Controls_11_2.geometry} material={nodes.Effect_Controls_11_2.material} />
        <mesh geometry={nodes.Effect_Controls_11_3.geometry} material={nodes.Effect_Controls_11_3.material} />
        <mesh geometry={nodes.Effect_Controls_12_1.geometry} material={nodes.Effect_Controls_12_1.material} />
        <mesh geometry={nodes.Effect_Controls_12_2.geometry} material={nodes.Effect_Controls_12_2.material} />
        <mesh geometry={nodes.Effect_Controls_12_3.geometry} material={nodes.Effect_Controls_12_3.material} />
        <mesh geometry={nodes.Effect_Controls_13_1.geometry} material={nodes.Effect_Controls_13_1.material} />
        <mesh geometry={nodes.Effect_Controls_13_2.geometry} material={nodes.Effect_Controls_13_2.material} />
        <mesh geometry={nodes.Effect_Controls_13_3.geometry} material={nodes.Effect_Controls_13_3.material} />
        <mesh geometry={nodes.Effect_Controls_14_1.geometry} material={nodes.Effect_Controls_14_1.material} />
        <mesh geometry={nodes.Effect_Controls_14_2.geometry} material={nodes.Effect_Controls_14_2.material} />
        <mesh geometry={nodes.Effect_Controls_14_3.geometry} material={nodes.Effect_Controls_14_3.material} />
        <mesh geometry={nodes.USB_plate.geometry} material={nodes.USB_plate.material}  />
        <mesh geometry={nodes.DJ_controller_left_1.geometry} material={nodes.DJ_controller_left_1.material} />
        <mesh geometry={nodes.DJ_controller_left_2.geometry} material={nodes.DJ_controller_left_2.material} />
        <mesh geometry={nodes.DJ_controller_left_3.geometry} material={nodes.DJ_controller_left_3.material} />
        <mesh geometry={nodes.PP1_plate.geometry} material={nodes.PP1_plate.material}  />
        <mesh geometry={nodes.Active_loop_button2.geometry} material={nodes.Active_loop_button2.material} />
        <mesh geometry={nodes.DJ_controller_right_1.geometry} material={nodes.DJ_controller_right_1.material} />
        <mesh geometry={nodes.DJ_controller_right_2.geometry} material={nodes.DJ_controller_right_2.material} />
        <mesh geometry={nodes.DJ_controller_right_3.geometry} material={nodes.DJ_controller_right_3.material} />
        <mesh geometry={nodes.Turn_Controller_R.geometry} material={nodes.Turn_Controller_R.material} />
        <mesh geometry={nodes.Beat_sync_button2.geometry} material={nodes.Beat_sync_button2.material} />
        <mesh geometry={nodes.Bottom_part.geometry} material={nodes.Bottom_part.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/ddj400.gltf')
