/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import useRefs from 'react-use-refs'

export default function (props: any) {
  const { src, binds, ...other } = props
  const [group, fade, note, note_, turn, midi] = useRefs()

  const { nodes } = useGLTF(src) as any
  return (
    <group ref={group} {...other} dispose={null} position={[-0.06, 0, -0.19]} rotation={[Math.PI / 2, 0, 0]}>
      <group ref={midi} {...binds.midi({ref: midi})}>
        <mesh geometry={nodes.Case_Plane_1.geometry} material={nodes.Case_Plane_1.material} />
        <mesh geometry={nodes.Case_Plane_2.geometry} material={nodes.Case_Plane_2.material} />
      </group>
      <group ref={note} {...binds.note({ref: note})}>
        <mesh geometry={nodes.Buttons_2_Plane007_1.geometry} material={nodes.Buttons_2_Plane007_1.material} />
        <mesh geometry={nodes.Buttons_2_Plane007_2.geometry} material={nodes.Buttons_2_Plane007_2.material} />
      </group>
      <group ref={fade} {...binds.fade({ref: fade})}>
        <mesh geometry={nodes.Sliders_Plane039_1.geometry} material={nodes.Sliders_Plane039_1.material} />
        <mesh geometry={nodes.Sliders_Plane039_2.geometry} material={nodes.Sliders_Plane039_2.material} />
      </group>
      <group ref={note_} {...binds.note({ref: note_})}>
        <mesh geometry={nodes.Buttons_Plane031_1.geometry} material={nodes.Buttons_Plane031_1.material} />
        <mesh geometry={nodes.Buttons_Plane031_2.geometry} material={nodes.Buttons_Plane031_2.material} />
      </group>
      <group ref={turn} {...binds.turn(turn)}>
        <mesh
          geometry={nodes.Potentiometers_Cylinder008.geometry}
          material={nodes.Potentiometers_Cylinder008.material}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/Nano.gltf')
