/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function (props: any) {
  const { src, ...other } = props
  const group = useRef()
  const { nodes, materials } = useGLTF(src) as any
  return (
    <group ref={group} {...other} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Case_Plane_1.geometry} material={nodes.Case_Plane_1.material} />
        <mesh geometry={nodes.Case_Plane_2.geometry} material={nodes.Case_Plane_2.material} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Buttons_2_Plane007_1.geometry} material={nodes.Buttons_2_Plane007_1.material} />
        <mesh geometry={nodes.Buttons_2_Plane007_2.geometry} material={nodes.Buttons_2_Plane007_2.material} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Buttons_Plane031_1.geometry} material={nodes.Buttons_Plane031_1.material} />
        <mesh geometry={nodes.Buttons_Plane031_2.geometry} material={nodes.Buttons_Plane031_2.material} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Faders_Plane039_1.geometry} material={nodes.Faders_Plane039_1.material} />
        <mesh geometry={nodes.Faders_Plane039_2.geometry} material={nodes.Faders_Plane039_2.material} />
      </group>
      <mesh
        geometry={nodes.Potentiometers_Cylinder008.geometry}
        material={nodes.Potentiometers_Cylinder008.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/nanokontrol.gltf')
